from pathlib import Path

path = Path("aigateway-api/src/aigateway_api/admin_routes.py")
text = path.read_text(encoding="utf-8")
old = '''        if use_local_embedding:\n            def _load_local_embedding_model():\n                # 从配置读取模型名，默认使用 Qwen3-Embedding-0.6B\n                from .app_state import get_state\n\n                _cfg_mgr = getattr(get_state(), "config_manager", None)\n                _emb_cfg = _cfg_mgr.get("embedding", {}) if _cfg_mgr else {}\n                _model_name = _emb_cfg.get("model", "Qwen/Qwen3-Embedding-0.6B")\n                _device = _emb_cfg.get("device", "auto")\n                _model_kwargs = {} if _device == "auto" else {"device": _device}\n                return SentenceTransformer(_model_name, **_model_kwargs)\n'''
new = '''        if use_local_embedding:\n            # Preserve the legacy test/integration injection point while rejecting\n            # stale non-model objects left in the process cache. Cache cleanup is\n            # allowed only while no load, release, or inference lease is active.\n            embedding_model_runtime.discard_invalid_if_idle(\n                lambda model: not callable(getattr(model, "encode", None))\n            )\n\n            def _load_local_embedding_model():\n                existing_model = _get_embedding_model()\n                if existing_model is not None:\n                    return existing_model\n\n                # 从配置读取模型名，默认使用 Qwen3-Embedding-0.6B\n                from .app_state import get_state\n\n                _cfg_mgr = getattr(get_state(), "config_manager", None)\n                _emb_cfg = _cfg_mgr.get("embedding", {}) if _cfg_mgr else {}\n                _model_name = _emb_cfg.get("model", "Qwen/Qwen3-Embedding-0.6B")\n                _device = _emb_cfg.get("device", "auto")\n                _model_kwargs = {} if _device == "auto" else {"device": _device}\n                return SentenceTransformer(_model_name, **_model_kwargs)\n'''
if old not in text:
    raise SystemExit("target block not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
